feat: add Homepage
PD-Andal-BEM-KM-2022/database-kemasyarakatan pull request #6
Opened 2022-12-24 05:09 UTC by frhnfrnk

2022-12-24 08:01 UTC, naragift reviewed
No need login button on navbar and posts gap can be a little bit more thinner.

2022-12-29 14:39 UTC, yzdnaufan commented
pake branch kamu aja han buat FE nya.

2022-12-29 14:39 UTC, yzdnaufan commented
> pake branch kamu aja han buat FE nya.
@frhnfrnk

2022-12-29 14:40 UTC, yzdnaufan requested changes
change branch destination

2023-01-02 13:20 UTC, yzdnaufan approved these changes

2023-01-02 16:10 UTC, merged